---
- name: restart ssh
  service:
    name: "{{ ssh_service }}"
    state: restarted

- name: reload ssh
  service:
    name: "{{ ssh_service }}"
    state: reloaded

- name: restart fail2ban
  service:
    name: fail2ban
    state: restarted

- name: save iptables
  command: /etc/init.d/iptables save
  when: ansible_facts["os_family"] == "Alpine"
