---
- name: Install Alpine common packages
  apk:
    name: "{{ common_packages + alpine_extra_packages }}"
    state: present
  when: ansible_facts["os_family"] == "Alpine"

- name: Install Debian common packages
  apt:
    name: "{{ common_packages + debian_extra_packages }}"
    state: present
    update_cache: yes
  when: ansible_facts["os_family"] == "Debian"
