---
# SSH Configuration Defaults
ssh_port: 22
ssh_permit_root_login: "no"
ssh_password_auth: "no"
ssh_challenge_response: "no"
ssh_allow_users: []

# Service Names (usually set in OS-specific tasks, but good to have defaults)
ssh_service_debian: ssh
ssh_service_alpine: sshd
